version: "3"

services:
  # PostgreSQL - Data Warehouse
  postgres:
    image: postgres:14
    container_name: nyc_taxi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nyc_taxi_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  postgres-init:
    image: postgres:14
    container_name: postgres-init
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: sh -c "until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done && psql -h postgres -U postgres -f /docker-entrypoint-initdb.d/initdb.sql"
    depends_on:
      postgres:
        condition: service_healthy
  # MinIO - Data Lake
  minio:
    image: minio/minio
    container_name: nyc_taxi_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Airflow avec image personnalisée
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    depends_on:
      - postgres
      - postgres-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_UID: 50000
    command: version
    user: "50000:0"
    volumes:
      - ./airflow:/opt/airflow

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "airflow_secret_key"
    command: webserver
    ports:
      - "8080:8080"
    user: "50000:0"
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/dags/scripts
      - ./jars:/opt/airflow/dags/jars
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: scheduler
    user: "50000:0"
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/dags/scripts
      - ./jars:/opt/airflow/dags/jars

  # Spark Master (toujours utile pour le monitoring)
  spark-master:
    image: bitnami/spark:3.3.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8181:8080"
      - "7077:7077"
    volumes:
      - ./spark/apps:/opt/spark/apps
      - ./spark/data:/opt/spark/data

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.3.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./spark/apps:/opt/spark/apps
      - ./spark/data:/opt/spark/data

  # dbt container
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: dbt
    depends_on:
      - postgres
    volumes:
      - ./dbt:/usr/app/dbt
    # Ajouter ces lignes pour remplacer l'ENTRYPOINT du Dockerfile
    entrypoint: ["/bin/bash", "-c"]
    # Commande à exécuter : installer pytz et garder le conteneur en fonctionnement
    command: ["pip install pytz && tail -f /dev/null"]

volumes:
  postgres_data:
  minio_data:
